# permissions for end users to view audits.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: audit-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: namespace-reporter
    app.kubernetes.io/part-of: namespace-reporter
    app.kubernetes.io/managed-by: kustomize
  name: audit-viewer-role
rules:
- apiGroups:
  - report.arpan.io
  resources:
  - audits
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - report.arpan.io
  resources:
  - audits/status
  verbs:
  - get
