---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - get
  - list
- apiGroups:
  - report.arpan.io
  resources:
  - audits
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - report.arpan.io
  resources:
  - audits/finalizers
  verbs:
  - update
- apiGroups:
  - report.arpan.io
  resources:
  - audits/status
  verbs:
  - get
  - patch
  - update
