apiVersion: report.arpan.io/v1
kind: Audit
metadata:
  labels:
    app.kubernetes.io/name: namespace-reporter
    app.kubernetes.io/managed-by: kustomize
  name: audit-sample
spec:
  selector:
    test: "hello"
  reportingComponents:
  - "Health"
